name: Vincent - Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-656745c1c42b8a25db0e596b-87c63c6701ff28f67708204d74ad22f06b
      - name: Run API tests
        run: |
          postman collection run 15060793-71debd3d-f5c4-4394-a47c-59d5b0133a45 -i 15060793-c35b59d5-3fe7-4ee3-a544-6137e75cbbdb
