name: Vincent - Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-65be231210cc130001a5f846-36749bee753da46715e7184b448af24063
      - name: Run API tests
        run: |
          postman collection run 15060793-7c7c8688-d7b9-4e0b-8dcb-1584e2d384cc -i 15060793-2189a037-c282-4085-beb7-8f5fa318d387
